task1: task1.c
	gcc -o task1 task1.c -lm

task2: task2.c
	gcc -o task2 task2.c -lm

task3: task3.c
	gcc -o task3 task3.c -lm

task4: task4.c
	gcc -o task4 task4.c -lm

task5: task5.c
	gcc -o task5 task5.c -lm