#Lab Group 20: Daniel Nucci ,Avdon Rački, Nikola Soldatovic, Owen Stoll
#SOFE 3950 Lab 3: Sudoku Solution Verification
sudoku_checker: sudoku_checker.c
	gcc -Wall -Wextra -std=c99 -pthread sudoku_checker.c -o sudoku_checker
