task1: task1.c
	gcc -Wall -Wextra -std=c99 -pthread -o task1 task1.c -lm

task2: task2.c
	gcc -Wall -Wextra -pthread -std=c99 -o task2 task2.c -lm

task3: task3.c
	gcc -Wall -Wextra -pthread -std=c99 -o task3 task3.c -lm

task4: task4.c
	gcc -Wall -Wextra -pthread -std=c99 -o task4 task4.c -lm

task5: task5.c
	gcc -Wall -Wextra -pthread -std=c99 -o task5 task5.c -lm